FROM ubuntu:22.04
SHELL ["/bin/bash", "-c"]
# Set the timezone info because otherwise tzinfo blocks install
# flow and ignores the non-interactive frontend command 🤬🤬🤬
RUN ln -snf /usr/share/zoneinfo/America/New_York /etc/localtime && echo "/usr/share/zoneinfo/America/New_York" > /etc/timezone

# Core system packages
RUN apt-get update --fix-missing
RUN apt install -y software-properties-common wget curl gpg gcc git make g++ unzip

# Install miniconda to /miniconda
RUN curl -LO http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN bash Miniconda3-latest-Linux-x86_64.sh -p /miniconda -b
RUN rm Miniconda3-latest-Linux-x86_64.sh
ENV PATH=/miniconda/bin:${PATH}
RUN conda update -y conda

RUN apt install -y apt-utils

ENV FORCE_CUDA="0"
RUN conda install -y numpy python=3.11 python=3.11 pytorch==2.3 torchvision torchaudio cpuonly fvcore iopath -c pytorch -c pytorch3d -c fvcore -c iopath -c conda-forge

# Install PyTorch3d from source
RUN git clone https://github.com/facebookresearch/pytorch3d.git /pytorch3d
WORKDIR /pytorch3d
# Checkout 0.7.6
RUN git checkout f34104cf6ebefacd7b7e07955ee7aaa823e616ac
RUN conda install -y ninja -c conda-forge
ENV MAX_JOBS=46
RUN pip install -v .

# YAPF versions newer than this break the MMCV config system
RUN pip install yapf==0.40.1
RUN pip install pyarrow pyquaternion open3d tensorboard pytorch-lightning==1.9.4 imageio black isort nntime
# This is required for Open3D to not blow up on startup
RUN apt install -y freeglut3-dev
RUN pip install mmcv==2.2.0

# Install nuscenes-devkit, forked to get rid of the matplotlib pegged dependency
RUN conda install -y matplotlib=3.8
RUN git clone https://github.com/kylevedder/nuscenes-devkit.git /nuscenes-devkit
WORKDIR /nuscenes-devkit
RUN pip install -e setup
RUN pip install FastGeodis==1.0.5 --no-build-isolation

RUN git clone https://github.com/facebookresearch/co-tracker /cotracker
WORKDIR /cotracker
RUN git checkout e29e93831181413ff2691a3d910277c09fd87559
RUN pip install -e .
RUN pip install imageio[ffmpeg]

RUN apt install -y libxcb-xinerama0 libxcb-xinput0
RUN pip uninstall PyQt5 -y
RUN pip uninstall opencv-python -y
RUN pip install opencv-python

RUN pip install bucketed-scene-flow-eval==2.0.13
ENV PYTHONPATH=/project:/bucketed_scene_flow_eval:/:${PYTHONPATH}

# Setup environment to support running as non-root user
ENV HOME=/home/user
RUN mkdir /payload_files
RUN chmod 777 /payload_files
COPY bashrc /payload_files/bashrc
WORKDIR /project
COPY entrypoint.sh /entrypoint.sh
RUN chmod 777 /entrypoint.sh
RUN chmod 777 /home

ENTRYPOINT ["/entrypoint.sh"]
