FROM lscr.io/linuxserver/blender:latest
SHELL ["/bin/bash", "-c"]
# Set the timezone info because otherwise tzinfo blocks install
# flow and ignores the non-interactive frontend command 🤬🤬🤬
RUN ln -snf /usr/share/zoneinfo/America/New_York /etc/localtime && echo "/usr/share/zoneinfo/America/New_York" > /etc/timezone

# Core system packages
RUN apt-get update --fix-missing
RUN apt install -y software-properties-common wget curl gpg gcc git make g++ unzip apt-utils

RUN /blender/4.1/python/bin/python3.11 -m pip install matplotlib==3.8.4

RUN git clone https://github.com/kylevedder/nuscenes-devkit.git /nuscenes-devkit
WORKDIR /nuscenes-devkit
RUN mkdir -p python-sdk/nuscenes_devkit/egg-info
RUN /blender/4.1/python/bin/python3.11 -m pip install ./setup

RUN /blender/4.1/python/bin/python3.11 -m pip install bucketed-scene-flow-eval==2.0.16

WORKDIR /project
