_base_ = "./bucketed_flow_test_av2_class_scaled.py"

BACKGROUND_CATEGORIES = ['-1BACKGROUND']

STUFF_CATEGORIES = [
    'BOLLARD',
    'CONSTRUCTION_BARREL',
    'CONSTRUCTION_CONE',
    'MOBILE_PEDESTRIAN_CROSSING_SIGN',
    'SIGN',
    'STOP_SIGN',
    
]

PEDESTRIAN_CATEGORIES = [
    'PEDESTRIAN', 'STROLLER', 'WHEELCHAIR', 'OFFICIAL_SIGNALER'
]
SMALL_VEHICLE_CATEGORIES = [
    'BICYCLE', 'BICYCLIST', 'MOTORCYCLE', 'MOTORCYCLIST', 'WHEELED_DEVICE',
    'WHEELED_RIDER'
]
VEHICLE_CATEGORIES = [
    'ARTICULATED_BUS', 'BOX_TRUCK', 'BUS', 'LARGE_VEHICLE', 'RAILED_VEHICLE',
    'REGULAR_VEHICLE', 'SCHOOL_BUS', 'TRUCK', 'TRUCK_CAB', 'VEHICULAR_TRAILER',
    'TRAFFIC_LIGHT_TRAILER', 'MESSAGE_BOARD_TRAILER'
]
ANIMAL_CATEGORIES = ['ANIMAL', 'DOG']

METACATAGORIES = {
    "BACKGROUND": BACKGROUND_CATEGORIES,
    "STUFF": STUFF_CATEGORIES,
    "PEDESTRIAN": PEDESTRIAN_CATEGORIES,
    "SMALL_MOVERS": SMALL_VEHICLE_CATEGORIES,
    "LARGE_MOVERS": VEHICLE_CATEGORIES
}

test_dataset = dict(
    args=dict(eval_type="bucketed_epe",
              eval_args=dict(_delete_=True, meta_class_lookup=METACATAGORIES)))
