BACKGROUND_CATEGORIES = ['BACKGROUND']

ROAD_SIGNS = [
    'BOLLARD',
    'CONSTRUCTION_BARREL',
    'CONSTRUCTION_CONE',
    'MOBILE_PEDESTRIAN_CROSSING_SIGN',
    'SIGN',
    'STOP_SIGN',
    'MESSAGE_BOARD_TRAILER',
    'TRAFFIC_LIGHT_TRAILER',
]
PEDESTRIAN_CATEGORIES = [
    'PEDESTRIAN', 'STROLLER', 'WHEELCHAIR', 'OFFICIAL_SIGNALER'
]

WHEELED_VRU = [
    'BICYCLE', 'BICYCLIST', 'MOTORCYCLE', 'MOTORCYCLIST', 'WHEELED_DEVICE',
    'WHEELED_RIDER'
]

CAR = ['REGULAR_VEHICLE']

OTHER_VEHICLES = [
    'BOX_TRUCK', 'LARGE_VEHICLE', 'RAILED_VEHICLE', 'TRUCK', 'TRUCK_CAB',
    'VEHICULAR_TRAILER', 'ARTICULATED_BUS', 'BUS', 'SCHOOL_BUS'
]

METACATAGORIES = {
    "BACKGROUND": BACKGROUND_CATEGORIES,
    "ROAD_SIGNS": ROAD_SIGNS,
    "CAR": CAR,
    "PEDESTRIAN": PEDESTRIAN_CATEGORIES,
    "WHEELED_VRU": WHEELED_VRU,
    "OTHER_VEHICLES": OTHER_VEHICLES,
}